### ISSUE TITLE
Adding some Bitwarden recommendations

### ISSUE THREAD

**Issue by cardboard849105** [yuuire/guide#59]
I suggest changing the password hash function from PBKDF2(default) to Argon2id since Argon2id is much more cryptographically secure.
It is available through settings>security>keys>KDF algorithm>argon2id
The same content is also recommended in privacyguides.org

**Comment by yuuire** [comment]
Thanks for your suggestion! I've added your recommendation to the [password managers section](https://guide.yuuire.com/privacy-settings/software/password-managers/bitwarden) :smiley:
